### PR TITLE
{LANDING_PAGE] Add how to install and release section + fix mobile menu

### LINKED ISSUE #37: [BUG][LANDING PAGE] Menu on mobile devices might be cut
**Steps to reproduce:**

1. Open landing page on mobile device, in portrait mode
2. Click on hamburger menu
3. Bottom of menu would be cut

**Screens with reproduction:**
screen_repro

**Devices to reproduce:**
- Samsung Galaxy S21 FE, any browser
- possibly others

### PR DESCRIPTION
**Pull request by Vakme**

### CODE REVIEW

**Comment by Udiknedormin** [comment]
Task linked: [CU-862j800vh Add "how to install" and "Release" section](https://app.clickup.com/t/862j800vh)

File: LandingPage/src/api/use-api.composable.ts [hunk 1]
```diff
@@ -25,3 +30,48 @@ export const useTeamContent = () => {
...
+export const useInstallationContent = () => {
+  const data = ref<string | null>(null);
+
+  const getData = async (locale: typeof i18n.global.locale) => {
+    //TODO: change markdowns structure
+    const startInstallationSection = i18n.global.t("INSTALLATION_SEPARATOR");
+    const res = await getInstallationContent(locale);
+    data.value = DOMPurify.sanitize(
+      marked.parse(res.split(startInstallationSection)[1])
+    );
```
Comment (Udiknedormin) [inline LandingPage/src/api/use-api.composable.ts:43]: Is it split by the work "Installation"? If so, that doesn't seem very safe --- the word could be used earlier on in the description somewhere.

Wouldn't it be better for us to simply split that file into multiple files, e.g.
* about
* companion-list
* installation

Or something of the kind?

File: LandingPage/src/components/ReleaseCard.vue [hunk 2]
```diff
@@ -0,0 +1,103 @@
...
+  </div>
+</template>
+
+<script setup lang="ts">
+import { useLatestRelease } from "@/api/use-api.composable";
+import { Release } from "@/api/github/release.schema";
+import { ref, Ref, UnwrapRef } from "vue";
+import { filesize } from "filesize";
+
+const release: Ref<UnwrapRef<Release | null>> = useLatestRelease();
```
Comment (Udiknedormin) [inline LandingPage/src/components/ReleaseCard.vue]: Wouldn't it be better if the ReleaseCard used any release it's passed? That way it would be really simple to use the same component for a list of e.g. last five major releases, or the newest stable and newest dev releases.

**Review by Udiknedormin — COMMENTED** [review]
I'm not sure about the release card component and whenever we shouldn't split about.md into multiple files.

File: LandingPage/src/api/use-api.composable.ts (hunk 1 above)
Comment (Vakme) [reply LandingPage/src/api/use-api.composable.ts:43]: This is a temporary measure, I will split it after merging this PR

File: LandingPage/src/components/ReleaseCard.vue (hunk 2 above)
Comment (Vakme) [reply LandingPage/src/components/ReleaseCard.vue]: Good idea, thanks!

Comment (Vakme) [reply LandingPage/src/components/ReleaseCard.vue]: fixed

**Review by Udiknedormin — APPROVED** [review]
